/* eslint-env mocha */
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');

const SqliteBuilder = require('../../util/SqliteBuilder');
const Constant = require('../../constant/Constant');
const { fakeConn } = require('../fakeConn');

const ROUTE_XML = '<?xml version="1.0" encoding="UTF-8"?>'
    + '<ROUTE_ROOT VERSION="20260818120000">'
    + '<ROUTE code="100" display_code="100A" start_name="MERKEZ" end_name="TERMINAL"'
    + ' region_code="2" route_icon_url="u" route_color="FF0000" route_text_color="FFFFFF"/>'
    + '<ROUTE code="200" display_code="200B" start_name="A" end_name="B" region_code=""/>'
    + '</ROUTE_ROOT>';

const BUS_STOP_ROWS = [
    { BUS_STOP_ID: '45', NAME: 'MERKEZ', ZONE_ID: '1', LATITUDE: '37.0625',
        LONGITUDE: '37.3781', ALTITUDE: '850', MD5: 'abc' },
];

const PATH_ROWS = [
    { NAME: 'MERKEZ - TERMINAL', ROUTE_CODE: '100', DISPLAY_ROUTE_CODE: '100A',
        HALF_PROGRESS_TYPE: '1', PATH_CODE: 'P00001', DESCRIPTION: 'gidis' },
];

const PATH_STOP_ROWS = [
    { PATH_CODE: 'P00001', BUS_STOP_ID: 45, SEQ_NO: 1, ARRIVAL_OFFSET: '2',
        ARRIVAL_OFFSET_SEC: '150', DEPARTURE_OFFSET: '2', DEPARTURE_OFFSET_SEC: '160',
        DISTANCE: '1200', STAGE_SEQ_NO: '1', ZONE_ID: '1' },
];

const FREE_CARD_ROWS = [
    { CSN: '0123456789', EXPIRED_DATE: '20301231', PASSENGER_TYPE: '01',
        BLACK_LIST: '0', CARD_NO: '6372430000000001' },
];

/** Answers each of the four statements the builder runs, plus the getroute procedure. */
function oracleFor(overrides = {}) {
    const routeXml = 'routeXml' in overrides ? overrides.routeXml : ROUTE_XML;
    return fakeConn((sql) => {
        if (sql.includes('sp_get_route')) {
            return { outBinds: { out_result: routeXml == null ? null : { getData: async () => routeXml } } };
        }
        if (sql.includes('FROM TMS_BUS_STOP WHERE')) return { rows: overrides.busStops || BUS_STOP_ROWS };
        if (sql.includes('FROM TMS_PATH_BUS_STOP WHERE')) return { rows: overrides.pathStops || PATH_STOP_ROWS };
        if (sql.includes('FROM mst_path a')) return { rows: overrides.paths || PATH_ROWS };
        if (sql.includes('FROM black_list_20')) return { rows: overrides.freeCards || FREE_CARD_ROWS };
        return undefined;
    });
}

/** Opens the generated bytes as a real database, which is what the device does with them. */
function openGenerated(buffer) {
    const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'valdb-')), 'generated.db');
    fs.writeFileSync(file, buffer);
    return new DatabaseSync(file, { readOnly: true });
}

// node:sqlite returns null prototype objects, so they are copied before being compared.
const rowsOf = (db, sql) => db.prepare(sql).all().map((r) => ({ ...r }));

/** The generators write into the app directories; anything they create is removed again. */
const preexisting = [Constant.ROUTE_DB_FILE_PATH, Constant.FREECARD_DB_FILE_PATH]
    .filter((dir) => fs.existsSync(dir));

after(() => {
    for (const dir of [Constant.ROUTE_DB_FILE_PATH, Constant.FREECARD_DB_FILE_PATH]) {
        if (!preexisting.includes(dir)) fs.rmSync(dir, { recursive: true, force: true });
    }
});

describe('route info db', () => {
    let db;
    let conn;

    before(async () => {
        conn = oracleFor();
        db = openGenerated(await SqliteBuilder.buildRouteInfo(conn, { opdate: '20260818' }, 'test'));
    });

    after(() => db.close());

    it('creates all nine tables', () => {
        const names = rowsOf(db, "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
            .map((r) => r.name);
        assert.deepStrictEqual(names, ['MST_PATH', 'MST_ROUTE', 'MST_TRIP_TYPE', 'TMS_BUS_STOP',
            'TMS_PATH_BUS_STOP', 'TMS_ROUTE_PATH', 'TMS_ROUTE_SCHEDULE', 'TMS_SCHEDULE_PLAN',
            'TMS_VERSION']);
    });

    it('stamps seven fixed versions plus the one the route document carried', () => {
        const rows = rowsOf(db, 'SELECT FILE_NAME, VERSION FROM TMS_VERSION');
        assert.strictEqual(rows.length, 8);
        assert.strictEqual(rows.find((r) => r.FILE_NAME === 'MST_ROUTE').VERSION, '20260818120000');
        assert.strictEqual(rows.find((r) => r.FILE_NAME === 'MST_TRIP_TYPE').VERSION, '19700101000000');
        assert.ok(/^\d{8}000000$/.test(rows.find((r) => r.FILE_NAME === 'TMS_BUS_STOP').VERSION));
    });

    it('takes the routes from the getroute document', () => {
        const rows = rowsOf(db, 'SELECT * FROM MST_ROUTE ORDER BY ROUTE_CODE');
        assert.strictEqual(rows.length, 2);
        assert.strictEqual(rows[0].DISPLAY_CODE, '100A');
        assert.strictEqual(rows[0].LINE_START_NAME, 'MERKEZ');
        assert.strictEqual(rows[0].REGION_CODE, 2);
        assert.strictEqual(rows[1].REGION_CODE, 0, 'an unusable region code becomes zero');
    });

    it('asks for the full route document whatever the caller sent', () => {
        const call = conn.matching('sp_get_route')[0];
        assert.strictEqual(call.binds.version, '19700101000000');
    });

    it('binds the three literals Java put on every bus stop row', () => {
        const row = rowsOf(db, 'SELECT * FROM TMS_BUS_STOP')[0];
        assert.strictEqual(row.STOP_ID, 45);
        assert.strictEqual(row.RAD, 10);
        assert.strictEqual(row.PARENT, 0);
        assert.strictEqual(row.TYPE, 0);
        assert.strictEqual(row.LAT, 37.0625);
    });

    it('fills MST_PATH and TMS_ROUTE_PATH from the one query', () => {
        // The path stop query repeats the same join in a subquery, so match on the projection.
        assert.strictEqual(conn.matching('SELECT UPPER(a.path_name)').length, 1);
        assert.deepStrictEqual(rowsOf(db, 'SELECT * FROM MST_PATH'),
            [{ PATH_CODE: 'P00001', PATH_NAME: 'MERKEZ - TERMINAL', DESCRIPTION: 'gidis' }]);
        assert.deepStrictEqual(rowsOf(db, 'SELECT * FROM TMS_ROUTE_PATH'),
            [{ ROUTE_CODE: '100', PATH_CODE: 'P00001', DIRECTION: '1' }]);
    });

    it('keeps the minute offset and the second offset in their own columns', () => {
        const row = rowsOf(db, 'SELECT * FROM TMS_PATH_BUS_STOP')[0];
        assert.strictEqual(row.ARRIVAL_OFFSET, 2);
        assert.strictEqual(row.ARRIVAL_OFFSET_SEC, 150);
        assert.strictEqual(row.DEPARTURE_OFFSET_SEC, 160);
        assert.strictEqual(row.BUS_STOP_ID, 45);
    });

    it('leaves the three plan tables empty for the device to fill', () => {
        for (const table of ['MST_TRIP_TYPE', 'TMS_SCHEDULE_PLAN', 'TMS_ROUTE_SCHEDULE']) {
            assert.strictEqual(rowsOf(db, `SELECT * FROM ${table}`).length, 0, table);
        }
    });

    it('keeps the misspelled column types, which decide the affinity', () => {
        const ddl = rowsOf(db,
            "SELECT sql FROM sqlite_master WHERE name='TMS_PATH_BUS_STOP' AND type='table'")[0].sql;
        assert.ok(ddl.includes('MUMERIC(4)'), 'ARRIVAL_OFFSET keeps its typo');
        assert.ok(ddl.includes('NUMBERIC(3)'), 'STAGE_SEQ_NO keeps its typo');
    });

    it('creates every index the Java file had', () => {
        const names = rowsOf(db, "SELECT name FROM sqlite_master WHERE type='index' AND sql IS NOT NULL")
            .map((r) => r.name).sort();
        assert.deepStrictEqual(names, ['idxTMS_ROUTE_SCHEDULE', 'idx_MST_PATH', 'idx_MST_ROUTE',
            'idx_TMS_BUS_STOP', 'idx_TMS_PATH_BUS_STOP', 'idx_TMS_ROUTE_PATH']);
    });
});

describe('route info db without a route document', () => {
    it('still produces a usable file with an empty MST_ROUTE', async () => {
        const data = await SqliteBuilder.buildRouteInfo(oracleFor({ routeXml: null }),
            { opdate: '20260818' }, 'test');
        const db = openGenerated(data);
        assert.strictEqual(rowsOf(db, 'SELECT * FROM MST_ROUTE').length, 0);
        assert.strictEqual(rowsOf(db, 'SELECT * FROM TMS_VERSION').length, 7,
            'no MST_ROUTE version row without a document');
        db.close();
    });
});

describe('free card db', () => {
    it('copies black_list_20 into Tbl_RFCARD_FREE', async () => {
        const db = openGenerated(await SqliteBuilder.buildFreeCard(oracleFor(), 'test'));
        assert.deepStrictEqual(rowsOf(db, 'SELECT * FROM Tbl_RFCARD_FREE'),
            // black_list is declared "number", so SQLite stores the bound text as an integer.
            [{ csn: '0123456789', expired_date: '20301231', passenger_type: '01',
                black_list: 0, card_no: '6372430000000001' }]);
        db.close();
    });

    it('fails generation on a repeated card serial, as the unique index demands', async () => {
        const duplicated = [FREE_CARD_ROWS[0], { ...FREE_CARD_ROWS[0], CARD_NO: 'other' }];
        await assert.rejects(() => SqliteBuilder.buildFreeCard(oracleFor({ freeCards: duplicated }), 'test'),
            (e) => e.message === 'Error executing SQLite generation');
    });
});

describe('generated file on disk', () => {
    it('is readable again through the cache path', async () => {
        await SqliteBuilder.buildFreeCard(oracleFor(), 'test');
        const cached = SqliteBuilder.readCached(Constant.FREECARD_DB_FILE_PATH);

        assert.ok(cached, 'today\'s file is found');
        assert.strictEqual(cached.subarray(0, 15).toString('utf8'), 'SQLite format 3');
    });

    it('answers with null when nothing has been generated', () => {
        assert.strictEqual(SqliteBuilder.readCached(path.join(os.tmpdir(), 'no-such-validator-dir')), null);
    });
});
